### PR TITLE
Fix a few typos in README files

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Comment by bkamins** [comment]
Thank you!

**Comment by pitmonticone** [comment]
Hi @bkamins, 

Thank you very much for making this material open for free. 

Have the lectures been recorded and, if so, will they be publicly available later?

**Comment by bkamins** [comment]
Yes. The material will be made available on YouTube. We will update the README.md in the repository when it is ready.

**Comment by pitmonticone** [comment]
Glad to hear that! Thank you very much.

**Pull request merged**
